<../../../mkconfig

TARG=\
	shttpd.dis\

SYSMODULES=\
	mhttp.m\
	arg.m\
	attrdb.m\
	bufio.m\
	daytime.m\
	draw.m\
	encoding.m\
	env.m\
	ip.m\
	keyring.m\
	regex.m\
	security.m\
	sh.m\
	string.m\
	sys.m\

DISBIN=$ROOT/dis/ip

<$ROOT/mkfiles/mkdis
